SELECT TB.ID,IF(TB.PER<=0.25,"CRITICAL",IF(TB.PER<=0.50,"HIGH",IF(TB.PER<=0.75,"MEDIUM","LOW")))AS COLONY_NAME
FROM
(SELECT ID,PERCENT_RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS PER FROM ECOLI_DATA) AS TB
ORDER BY TB.ID ASC