SELECT INGREDIENT_TYPE,SUM(TOTAL_ORDER)AS TOTAL_ORDER
FROM
(SELECT B.INGREDIENT_TYPE,A.TOTAL_ORDER
FROM
FIRST_HALF AS A
JOIN ICECREAM_INFO AS B ON A.FLAVOR=B.FLAVOR)AS C
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC